### ISSUE TITLE
1 second behind

### ISSUE THREAD

**Issue by briang123** [saketh-kowtha/time-zone-converter#1]
When comparing to my macbook clock, your clock appears to be one second behind.

**Comment by saketh-kowtha** [comment]
@briang123 can you please check again. I hope my changes will solve this issue. If you confirm i will close this issue.

**Comment by briang123** [comment]
Not on my computer, but tested on iPhone and it appears to match.

**Comment by briang123** [comment]
Maybe double check the time at the time you click the voice button. That also appears to be a second off. For instance, if I click on the button when the click just shows 30 sec the voice tells me 29 sec
